### PR TITLE
Add name and description to shell : )

### PR DESCRIPTION
**Pull request by jakeisnt**
- Add `name` attribute to flake
- Abstract `name` and `description` attributes as top-level declarations
- Add both attributes to the default devShell

### CODE REVIEW

**Comment by mitchellh** [comment]
Thanks this looks good!

**Comment by jakeisnt** [comment]
This should be reverted!

It still works because `shell.nix` pulls in `flake-compat`, but it fails to actually register as a flake because of some strange flake evaluation rules: https://github.com/NixOS/nix/issues/3966

**Comment by mitchellh** [comment]
No problem, easy to slip through since its in a template. I'll revert when I can.

**Comment by mitchellh** [comment]
Done

**Pull request merged**
